name: Create artifact

on:
  workflow_dispatch:
    inputs:
      branch:
        type: string
        description: Branch name
        default: develop

permissions:
  contents: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          token_format: "access_token"
          workload_identity_provider: projects/${{ secrets.PROJECT_NUMBER }}/locations/global/workloadIdentityPools/${{ secrets.POOL_ID }}/providers/${{ secrets.PROVIDER_ID }}
          project_id: ${{ secrets.PROJECT_ID }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}
          access_token_scopes: "https://www.googleapis.com/auth/spreadsheets"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Create artifact
        run: |
          python src/create.py

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            data/output/translation_file/ja_jp_data.dat
            data/output/translation_file/ja_jp_data.dir
          make_latest: true
